stages: [lint, test, build, security, promote, deploy]


workflow:
  rules:
    - if: '$CI_COMMIT_TAG'                                # Запускати на тегах
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'  # Запускати на Merge Request
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'  # Уникаємо дублювання (якщо є MR, не запускати на гілці)
      when: never
    - if: '$CI_COMMIT_BRANCH'                             # Запускати на push в гілку

default:
  tags: ["gitlab_build_runner"]

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/apps"
  TAG_REGEX: '^v1\.[0-9]{4}\.[0-9]{2}(\.[0-9]+)?(-rc[0-9]*)?$'
  TRIVY_CACHE_DIR: ".trivycache/"

.release_only: &release_only
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v1\.[0-9]{4}\.[0-9]{2}(\.[0-9]+)?(-rc[0-9]*)?$/'
      when: always
    - when: never

.ssh_setup: &ssh_setup
  before_script:
    - apk add --no-cache openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan -p 17771 $SSH_HOST >> ~/.ssh/known_hosts

.promote_job: &promote_job
  stage: promote
  image: 
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
    - crane auth login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - crane tag "${IMAGE_NAME}:${CI_COMMIT_TAG}" "${TARGET_ENV}"
    - echo "✅ Promoted ${CI_COMMIT_TAG} to ${TARGET_ENV}"

# Шаблон для деплою
.deploy_job: &deploy_job
  stage: deploy
  image: alpine:latest
  <<: *ssh_setup
  script:
    - export IMAGE_DIGEST=$(cat digest.txt)
    - echo "Deploying Digest $IMAGE_DIGEST to ${TARGET_ENV}"
    - echo "Uploading migrations..."
    - tar -czf migrations.tar.gz -C migrations .
    - scp -o StrictHostKeyChecking=no  -P 17771 migrations.tar.gz $SSH_USER@$SSH_HOST:/tmp/migrations_${CI_PIPELINE_ID}.tar.gz
    - ssh -p 17771 $SSH_USER@$SSH_HOST  "bash /home/$SSH_USER/roulette-$TARGET_ENV/deploy/deploy.sh ${TARGET_ENV} ${TARGET_ENV} ${CI_COMMIT_TAG} ${CI_COMMIT_SHORT_SHA} ${IMAGE_DIGEST} /tmp/migrations_${CI_PIPELINE_ID}.tar.gz"

.rollback_job: &rollback_job
  stage: deploy
  image: alpine:latest
  <<: *ssh_setup
  script:
    - echo "Rolling back ${TARGET_ENV}..."
    - ssh -p 17771 $SSH_USER@$SSH_HOST  "bash /home/$SSH_USER/roulette-$TARGET_ENV/deploy/rollback.sh ${TARGET_ENV}"

.rollback_db_job: &rollback_db_job
  stage: deploy
  image: alpine:latest
  <<: *ssh_setup
  script:
    - echo "Rolling back DATABASE on ${TARGET_ENV}..."
    # Викликаємо rollback_db.sh (1 крок назад за замовчуванням)
    - ssh -p 17771 $SSH_USER@$SSH_HOST  "bash /home/$SSH_USER/roulette-$TARGET_ENV/deploy/rollback_db.sh ${TARGET_ENV} 1"

# ============== LINT ==============
lint:dockerfile-hadolint:
  stage: lint
  image: ghcr.io/hadolint/hadolint:latest-alpine
  rules: [{ when: always }]
  script:
    - hadolint --version
    - |
      F="$(git ls-files | grep -Ei '(^|.*/)(Dockerfile(\..*)?$|.*Dockerfile.*)' || true)"; \
      [ -z "$F" ] && echo "No Dockerfiles" | tee hadolint.txt || hadolint --ignore DL3018 --failure-threshold error $F | tee hadolint.txt
  artifacts:
    when: always
    paths: [hadolint.txt]
    expire_in: 7 days
  allow_failure: true

lint:go-vet:
  stage: lint
  image: golang:1.25-alpine
  rules: [{ when: always }]
  before_script:
    - apk add --no-cache git
    - go mod download
  script:
    - go vet ./...

lint:go-govulncheck:
  stage: lint
  image: golang:1.25-alpine
  rules: [{ when: always }]
  before_script:
    - apk add --no-cache git
    - go install golang.org/x/vuln/cmd/govulncheck@latest
    - export PATH=$PATH:/go/bin
    - go mod download
  script:
    - govulncheck ./... | tee govulncheck.txt
  artifacts:
    when: always
    paths: [govulncheck.txt]
    expire_in: 7 days
  allow_failure: true

lint:go-gosec:
  stage: lint
  image: golang:1.25-alpine
  rules: [{ when: always }]
  before_script:
    - go install github.com/securego/gosec/v2/cmd/gosec@latest
    - export PATH=$PATH:/go/bin
    - go mod download
  script:
    - gosec -no-fail -fmt json -out gosec.json ./... # -no-fail <— чтобы job не падал
  artifacts:
    when: always
    paths: [gosec.json]
    expire_in: 7 days
  allow_failure: true

# ============== TEST ==============
test:go-unit:
  stage: test
  image: golang:1.25-alpine
  rules: [{ when: always }]
  before_script:
    - apk add --no-cache git build-base
    - go mod download
  script:
    - go test -race -covermode=atomic -coverprofile=coverage.out ./...
  artifacts:
    when: always
    paths: [coverage.out]
    expire_in: 7 days

build:kaniko:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v1\.[0-9]{4}\.[0-9]{2}(\.[0-9]+)?(-rc[0-9]*)?$/'
      when: always
    - when: never
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "gitlab-ci-token" "${CI_JOB_TOKEN}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${IMAGE_NAME}:${CI_COMMIT_TAG}"
      --destination "${IMAGE_NAME}:sandbox"
      --digest-file="${CI_PROJECT_DIR}/digest.txt"
      --build-arg "VERSION=${CI_COMMIT_TAG}"
      --build-arg "COMMIT=${CI_COMMIT_SHA}"
      --build-arg "BUILT_AT=${BUILD_DATE}"
      --label "org.opencontainers.image.created=${BUILD_DATE}"
      --label "org.opencontainers.image.version=${CI_COMMIT_TAG}"
      --label "org.opencontainers.image.revision=${CI_COMMIT_SHA}"
      --label "com.yourcompany.env=sandbox"
      --cache=true
      --cache-repo="${IMAGE_NAME}/cache"
  artifacts:
    paths:
      - digest.txt
    when: on_success

prepare:release:
  stage: build
  image: 
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v1\.[0-9]{4}\.[0-9]{2}(\.[0-9]+)?(-rc[0-9]*)?$/'
      when: always
    - when: never
  needs: ["build:kaniko"]    
  script:
    - export IMAGE_DIGEST=$(cat digest.txt)
    - mkdir -p release_pack
    - tar -czf release_pack/migrations.tar.gz -C migrations .
    - cp digest.txt release_pack/digest.txt
    - crane auth login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - crane export "${IMAGE_NAME}@${IMAGE_DIGEST}" | tar -xvf - -C release_pack --strip-components=1 app/roulette-bot app/roulette-admin app/roulette-rotator
  artifacts:
    name: "release-$CI_COMMIT_TAG"
    paths:
      - release_pack/

security:trivy:
  stage: security
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v1\.[0-9]{4}\.[0-9]{2}(\.[0-9]+)?(-rc[0-9]*)?$/'
      when: always
    - when: never   
  image: 
    name: aquasec/trivy:0.48.3
    entrypoint: [""]
  variables:
    TRIVY_USERNAME: "gitlab-ci-token"
    TRIVY_PASSWORD: "$CI_JOB_TOKEN"
  script:
    - export IMAGE_DIGEST=$(cat digest.txt)
    - echo "Scanning ${IMAGE_NAME}@${IMAGE_DIGEST}"
    # Скануємо конкретний хеш, а не тег (уникаємо підміни)
    - trivy image --exit-code 1 --severity CRITICAL,HIGH --ignore-unfixed --no-progress "${IMAGE_NAME}@${IMAGE_DIGEST}"
    - trivy image --no-progress "${IMAGE_NAME}@${IMAGE_DIGEST}"

promote:stage:
  stage: promote
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v1\.[0-9]{4}\.[0-9]{2}(\.[0-9]+)?(-rc[0-9]*)?$/'
      when: always
    - when: never    
  image: 
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  variables:
    TARGET_ENV: "stage"
  needs: ["security:trivy", "build:kaniko"]
  script:
    - export IMAGE_DIGEST=$(cat digest.txt)
    - crane auth login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # Тегуємо конкретний Digest тегом 'stage'
    - crane tag "${IMAGE_NAME}@${IMAGE_DIGEST}" "${TARGET_ENV}"

promote:prod:
  stage: promote
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v1\.[0-9]{4}\.[0-9]{2}(\.[0-9]+)?(-rc[0-9]*)?$/'
      when: always
    - when: never 
  image: 
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  variables:
    TARGET_ENV: "prod"
  needs: ["security:trivy", "build:kaniko"]
  when: manual
  script:
    - export IMAGE_DIGEST=$(cat digest.txt)
    - crane auth login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - crane tag "${IMAGE_NAME}@${IMAGE_DIGEST}" "${TARGET_ENV}"

deploy:sandbox:
  <<: [*deploy_job]
  variables:
    TARGET_ENV: "sandbox"
    SSH_HOST: $SSH_HOST_SANDBOX 
    SSH_USER: $SSH_USER_SANDBOX
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY_SANDBOX         
  needs: ["build:kaniko"]
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v1\.[0-9]{4}\.[0-9]{2}(\.[0-9]+)?(-rc[0-9]*)?$/'
      when: manual
    - when: never  

deploy:stage:
  <<: [*deploy_job]
  variables:
    TARGET_ENV: "stage"
    SSH_HOST: $SSH_HOST_STAGE 
    SSH_USER: $SSH_USER_STAGE
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY_STAGE         
  needs: ["promote:stage", "build:kaniko"]
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v1\.[0-9]{4}\.[0-9]{2}(\.[0-9]+)?(-rc[0-9]*)?$/'
      when: manual
    - when: never  

deploy:trigger-prod:
  stage: deploy
  variables:
    UPSTREAM_REF: $CI_COMMIT_TAG
    IMAGE_NAME: $IMAGE_NAME    
    TARGET_ENV: prod
  needs: ["promote:prod", "build:kaniko"]
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v1\.[0-9]{4}\.[0-9]{2}(\.[0-9]+)?(-rc[0-9]*)?$/'
      when: manual
    - when: never  
  trigger:
    project: infra/prod-deploy
    branch: master
    strategy: depend

rollback:db:stage:
  <<: [*rollback_db_job]  
  variables: 
    TARGET_ENV: stage
    SSH_HOST: $SSH_HOST_STAGE
    SSH_USER: $SSH_USER_STAGE
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY_STAGE
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v1\.[0-9]{4}\.[0-9]{2}(\.[0-9]+)?(-rc[0-9]*)?$/'
      when: manual
    - when: never  

rollback:stage:
  <<: [*rollback_job]    
  variables: 
    TARGET_ENV: stage
    SSH_HOST: $SSH_HOST_STAGE
    SSH_USER: $SSH_USER_STAGE
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY_STAGE
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v1\.[0-9]{4}\.[0-9]{2}(\.[0-9]+)?(-rc[0-9]*)?$/'
      when: manual
    - when: never  
