services:
  postgres:
    image: postgres:15-alpine
    container_name: roulette-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roulette
    volumes:
      - ./shared-data/postgresql:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    # ports:
    #   - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d roulette"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: roulette-pgadmin
    environment:
      SCRIPT_NAME: /pgadmin
      PGADMIN_PORT: 80
      PGADMIN_DEFAULT_EMAIL: postgres@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - ./shared-data/pgadmin:/var/lib/pgadmin
      - "./pgadmin4.config.json:/pgadmin4/servers.json"
    ports:
      - "8181:80"
    depends_on:
      postgres:
        condition: service_healthy

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roulette-bot
    command: ./roulette-bot
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/roulette?sslmode=disable
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  rotator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roulette-rotator
    command: ./roulette-rotator
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/roulette?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roulette-admin
    command: ./roulette-admin
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/roulette?sslmode=disable
      - ADMIN_PORT=8080
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - SESSION_SECRET=${SESSION_SECRET:-super_secret_key}
      - DISABLE_IP_FILTERS=true
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    