{
 "title": "User Status",
 "time": { "from": "2026-01-28T16:02:02.601Z", "to": "2026-01-28T17:56:45.360Z" },
 "panels": [
  {
   "title": "Total Ban",
   "type": "timeseries",
   "description": "Ban users",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(ban_triggered_total[5m])", "legendFormat": "{{ban_reason}}" }
   ]
  },
  {
   "title": "Captcha refresh",
   "type": "timeseries",
   "description": "Total Captcha refresh",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(captcha_refresh_total[5m])",
     "legendFormat": "{{refresh_reason}}"
    }
   ]
  },
  {
   "title": "Captcha triggers",
   "type": "timeseries",
   "description": "Captcha triggers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(captcha_triggered_total[5m])",
     "legendFormat": "{{captcha_reason}}"
    }
   ]
  },
  {
   "title": "Captcha passed",
   "type": "timeseries",
   "description": "Total Captcha passed",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(captcha_passed_total[5m])", "legendFormat": "{{passed_reason}}" }
   ]
  },
  {
   "title": "Captcha Lockout",
   "type": "timeseries",
   "description": "Total Captcha lockout",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(captcha_lockout_total[5m])",
     "legendFormat": "{{lockout_reason}}"
    }
   ]
  }
 ]
}