package bot

var (
	countries = []struct {
		Code     string // ISO 3166-1 alpha-2
		Emoji    string
		Name     string
		Favorite bool
	}{
		{"AD", "🇦🇩", "Andorra", false},
		{"AE", "🇦🇪", "United Arab Emirates", false},
		{"AF", "🇦🇫", "Afghanistan", false},
		{"AG", "🇦🇬", "Antigua and Barbuda", false},
		{"AI", "🇦🇮", "Anguilla", false},
		{"AL", "🇦🇱", "Albania", false},
		{"AM", "🇦🇲", "Armenia", false},
		{"AO", "🇦🇴", "Angola", false},
		{"AQ", "🇦🇶", "Antarctica", false},
		{"AR", "🇦🇷", "Argentina", false},
		{"AS", "🇦🇸", "American Samoa", false},
		{"AT", "🇦🇹", "Austria", false},
		{"AU", "🇦🇺", "Australia", false},
		{"AW", "🇦🇼", "Aruba", false},
		{"AX", "🇦🇽", "Åland Islands", false},
		{"AZ", "🇦🇿", "Azerbaijan", false},
		{"BA", "🇧🇦", "Bosnia and Herzegovina", false},
		{"BB", "🇧🇧", "Barbados", false},
		{"BD", "🇧🇩", "Bangladesh", false},
		{"BE", "🇧🇪", "Belgium", false},
		{"BF", "🇧🇫", "Burkina Faso", false},
		{"BG", "🇧🇬", "Bulgaria", false},
		{"BH", "🇧🇭", "Bahrain", false},
		{"BI", "🇧🇮", "Burundi", false},
		{"BJ", "🇧🇯", "Benin", false},
		{"BL", "🇧🇱", "Saint Barthélemy", false},
		{"BM", "🇧🇲", "Bermuda", false},
		{"BN", "🇧🇳", "Brunei Darussalam", false},
		{"BO", "🇧🇴", "Bolivia, Plurinational State of", false},
		{"BQ", "🇧🇶", "Bonaire, Sint Eustatius and Saba", false},
		{"BR", "🇧🇷", "Brazil", false},
		{"BS", "🇧🇸", "Bahamas", false},
		{"BT", "🇧🇹", "Bhutan", false},
		{"BV", "🇧🇻", "Bouvet Island", false},
		{"BW", "🇧🇼", "Botswana", false},
		{"BY", "🇧🇾", "Belarus", true},
		{"BZ", "🇧🇿", "Belize", false},
		{"CA", "🇨🇦", "Canada", false},
		{"CC", "🇨🇨", "Cocos (Keeling) Islands", false},
		{"CD", "🇨🇩", "Congo, Democratic Republic of the", false},
		{"CF", "🇨🇫", "Central African Republic", false},
		{"CG", "🇨🇬", "Congo", false},
		{"CH", "🇨🇭", "Switzerland", false},
		{"CI", "🇨🇮", "Côte d'Ivoire", false},
		{"CK", "🇨🇰", "Cook Islands", false},
		{"CL", "🇨🇱", "Chile", false},
		{"CM", "🇨🇲", "Cameroon", false},
		{"CN", "🇨🇳", "China", true},
		{"CO", "🇨🇴", "Colombia", false},
		{"CR", "🇨🇷", "Costa Rica", false},
		{"CU", "🇨🇺", "Cuba", false},
		{"CV", "🇨🇻", "Cabo Verde", false},
		{"CW", "🇨🇼", "Curaçao", false},
		{"CX", "🇨🇽", "Christmas Island", false},
		{"CY", "🇨🇾", "Cyprus", false},
		{"CZ", "🇨🇿", "Czechia", false},
		{"DE", "🇩🇪", "Germany", true},
		{"DJ", "🇩🇯", "Djibouti", false},
		{"DK", "🇩🇰", "Denmark", false},
		{"DM", "🇩🇲", "Dominica", false},
		{"DO", "🇩🇴", "Dominican Republic", false},
		{"DZ", "🇩🇿", "Algeria", false},
		{"EC", "🇪🇨", "Ecuador", false},
		{"EE", "🇪🇪", "Estonia", false},
		{"EG", "🇪🇬", "Egypt", false},
		{"EH", "🇪🇭", "Western Sahara", false},
		{"ER", "🇪🇷", "Eritrea", false},
		{"ES", "🇪🇸", "Spain", false},
		{"ET", "🇪🇹", "Ethiopia", false},
		{"FI", "🇫🇮", "Finland", false},
		{"FJ", "🇫🇯", "Fiji", false},
		{"FK", "🇫🇰", "Falkland Islands (Malvinas)", false},
		{"FM", "🇫🇲", "Micronesia, Federated States of", false},
		{"FO", "🇫🇴", "Faroe Islands", false},
		{"FR", "🇫🇷", "France", true},
		{"GA", "🇬🇦", "Gabon", false},
		{"GB", "🇬🇧", "United Kingdom of Great Britain and Northern Ireland", true},
		{"GD", "🇬🇩", "Grenada", false},
		{"GE", "🇬🇪", "Georgia", false},
		{"GF", "🇬🇫", "French Guiana", false},
		{"GG", "🇬🇬", "Guernsey", false},
		{"GH", "🇬🇭", "Ghana", false},
		{"GI", "🇬🇮", "Gibraltar", false},
		{"GL", "🇬🇱", "Greenland", false},
		{"GM", "🇬🇲", "Gambia", false},
		{"GN", "🇬🇳", "Guinea", false},
		{"GP", "🇬🇵", "Guadeloupe", false},
		{"GQ", "🇬🇶", "Equatorial Guinea", false},
		{"GR", "🇬🇷", "Greece", false},
		{"GS", "🇬🇸", "South Georgia and the South Sandwich Islands", false},
		{"GT", "🇬🇹", "Guatemala", false},
		{"GU", "🇬🇺", "Guam", false},
		{"GW", "🇬🇼", "Guinea-Bissau", false},
		{"GY", "🇬🇾", "Guyana", false},
		{"HK", "🇭🇰", "Hong Kong", false},
		{"HM", "🇭🇲", "Heard Island and McDonald Islands", false},
		{"HN", "🇭🇳", "Honduras", false},
		{"HR", "🇭🇷", "Croatia", false},
		{"HT", "🇭🇹", "Haiti", false},
		{"HU", "🇭🇺", "Hungary", false},
		{"ID", "🇮🇩", "Indonesia", false},
		{"IE", "🇮🇪", "Ireland", false},
		{"IL", "🇮🇱", "Israel", false},
		{"IM", "🇮🇲", "Isle of Man", false},
		{"IN", "🇮🇳", "India", true},
		{"IO", "🇮🇴", "British Indian Ocean Territory", false},
		{"IQ", "🇮🇶", "Iraq", false},
		{"IR", "🇮🇷", "Iran, Islamic Republic of", false},
		{"IS", "🇮🇸", "Iceland", false},
		{"IT", "🇮🇹", "Italy", false},
		{"JE", "🇯🇪", "Jersey", false},
		{"JM", "🇯🇲", "Jamaica", false},
		{"JO", "🇯🇴", "Jordan", false},
		{"JP", "🇯🇵", "Japan", true},
		{"KE", "🇰🇪", "Kenya", false},
		{"KG", "🇰🇬", "Kyrgyzstan", false},
		{"KH", "🇰🇭", "Cambodia", false},
		{"KI", "🇰🇮", "Kiribati", false},
		{"KM", "🇰🇲", "Comoros", false},
		{"KN", "🇰🇳", "Saint Kitts and Nevis", false},
		{"KP", "🇰🇵", "Korea, Democratic People's Republic of", false},
		{"KR", "🇰🇷", "Korea, Republic of", false},
		{"KW", "🇰🇼", "Kuwait", false},
		{"KY", "🇰🇾", "Cayman Islands", false},
		{"KZ", "🇰🇿", "Kazakhstan", true},
		{"LA", "🇱🇦", "Lao People's Democratic Republic", false},
		{"LB", "🇱🇧", "Lebanon", false},
		{"LC", "🇱🇨", "Saint Lucia", false},
		{"LI", "🇱🇮", "Liechtenstein", false},
		{"LK", "🇱🇰", "Sri Lanka", false},
		{"LR", "🇱🇷", "Liberia", false},
		{"LS", "🇱🇸", "Lesotho", false},
		{"LT", "🇱🇹", "Lithuania", false},
		{"LU", "🇱🇺", "Luxembourg", false},
		{"LV", "🇱🇻", "Latvia", false},
		{"LY", "🇱🇾", "Libya", false},
		{"MA", "🇲🇦", "Morocco", false},
		{"MC", "🇲🇨", "Monaco", false},
		{"MD", "🇲🇩", "Moldova, Republic of", false},
		{"ME", "🇲🇪", "Montenegro", false},
		{"MF", "🇲🇫", "Saint Martin (French part)", false},
		{"MG", "🇲🇬", "Madagascar", false},
		{"MH", "🇲🇭", "Marshall Islands", false},
		{"MK", "🇲🇰", "North Macedonia", false},
		{"ML", "🇲🇱", "Mali", false},
		{"MM", "🇲🇲", "Myanmar", false},
		{"MN", "🇲🇳", "Mongolia", false},
		{"MO", "🇲🇴", "Macao", false},
		{"MP", "🇲🇵", "Northern Mariana Islands", false},
		{"MQ", "🇲🇶", "Martinique", false},
		{"MR", "🇲🇷", "Mauritania", false},
		{"MS", "🇲🇸", "Montserrat", false},
		{"MT", "🇲🇹", "Malta", false},
		{"MU", "🇲🇺", "Mauritius", false},
		{"MV", "🇲🇻", "Maldives", false},
		{"MW", "🇲🇼", "Malawi", false},
		{"MX", "🇲🇽", "Mexico", false},
		{"MY", "🇲🇾", "Malaysia", false},
		{"MZ", "🇲🇿", "Mozambique", false},
		{"NA", "🇳🇦", "Namibia", false},
		{"NC", "🇳🇨", "New Caledonia", false},
		{"NE", "🇳🇪", "Niger", false},
		{"NF", "🇳🇫", "Norfolk Island", false},
		{"NG", "🇳🇬", "Nigeria", false},
		{"NI", "🇳🇮", "Nicaragua", false},
		{"NL", "🇳🇱", "Netherlands, Kingdom of the", false},
		{"NO", "🇳🇴", "Norway", false},
		{"NP", "🇳🇵", "Nepal", false},
		{"NR", "🇳🇷", "Nauru", false},
		{"NU", "🇳🇺", "Niue", false},
		{"NZ", "🇳🇿", "New Zealand", false},
		{"OM", "🇴🇲", "Oman", false},
		{"PA", "🇵🇦", "Panama", false},
		{"PE", "🇵🇪", "Peru", false},
		{"PF", "🇵🇫", "French Polynesia", false},
		{"PG", "🇵🇬", "Papua New Guinea", false},
		{"PH", "🇵🇭", "Philippines", false},
		{"PK", "🇵🇰", "Pakistan", false},
		{"PL", "🇵🇱", "Poland", true},
		{"PM", "🇵🇲", "Saint Pierre and Miquelon", false},
		{"PN", "🇵🇳", "Pitcairn", false},
		{"PR", "🇵🇷", "Puerto Rico", false},
		{"PS", "🇵🇸", "Palestine, State of", false},
		{"PT", "🇵🇹", "Portugal", false},
		{"PW", "🇵🇼", "Palau", false},
		{"PY", "🇵🇾", "Paraguay", false},
		{"QA", "🇶🇦", "Qatar", false},
		{"RE", "🇷🇪", "Réunion", false},
		{"RO", "🇷🇴", "Romania", false},
		{"RS", "🇷🇸", "Serbia", false},
		{"RU", "🇷🇺", "Russian Federation", true},
		{"RW", "🇷🇼", "Rwanda", false},
		{"SA", "🇸🇦", "Saudi Arabia", false},
		{"SB", "🇸🇧", "Solomon Islands", false},
		{"SC", "🇸🇨", "Seychelles", false},
		{"SD", "🇸🇩", "Sudan", false},
		{"SE", "🇸🇪", "Sweden", false},
		{"SG", "🇸🇬", "Singapore", false},
		{"SH", "🇸🇭", "Saint Helena, Ascension and Tristan da Cunha", false},
		{"SI", "🇸🇮", "Slovenia", false},
		{"SJ", "🇸🇯", "Svalbard and Jan Mayen", false},
		{"SK", "🇸🇰", "Slovakia", false},
		{"SL", "🇸🇱", "Sierra Leone", false},
		{"SM", "🇸🇲", "San Marino", false},
		{"SN", "🇸🇳", "Senegal", false},
		{"SO", "🇸🇴", "Somalia", false},
		{"SR", "🇸🇷", "Suriname", false},
		{"SS", "🇸🇸", "South Sudan", false},
		{"ST", "🇸🇹", "Sao Tome and Principe", false},
		{"SV", "🇸🇻", "El Salvador", false},
		{"SX", "🇸🇽", "Sint Maarten (Dutch part)", false},
		{"SY", "🇸🇾", "Syrian Arab Republic", false},
		{"SZ", "🇸🇿", "Eswatini", false},
		{"TC", "🇹🇨", "Turks and Caicos Islands", false},
		{"TD", "🇹🇩", "Chad", false},
		{"TF", "🇹🇫", "French Southern Territories", false},
		{"TG", "🇹🇬", "Togo", false},
		{"TH", "🇹🇭", "Thailand", false},
		{"TJ", "🇹🇯", "Tajikistan", false},
		{"TK", "🇹🇰", "Tokelau", false},
		{"TL", "🇹🇱", "Timor-Leste", false},
		{"TM", "🇹🇲", "Turkmenistan", false},
		{"TN", "🇹🇳", "Tunisia", false},
		{"TO", "🇹🇴", "Tonga", false},
		{"TR", "🇹🇷", "Türkiye", true},
		{"TT", "🇹🇹", "Trinidad and Tobago", false},
		{"TV", "🇹🇻", "Tuvalu", false},
		{"TW", "🇹🇼", "Taiwan, Province of China", false},
		{"TZ", "🇹🇿", "Tanzania, United Republic of", false},
		{"UA", "🇺🇦", "Ukraine", true},
		{"UG", "🇺🇬", "Uganda", false},
		{"UM", "🇺🇲", "United States Minor Outlying Islands", false},
		{"US", "🇺🇸", "United States of America", true},
		{"UY", "🇺🇾", "Uruguay", false},
		{"UZ", "🇺🇿", "Uzbekistan", false},
		{"VA", "🇻🇦", "Holy See", false},
		{"VC", "🇻🇨", "Saint Vincent and the Grenadines", false},
		{"VE", "🇻🇪", "Venezuela, Bolivarian Republic of", false},
		{"VG", "🇻🇬", "Virgin Islands (British)", false},
		{"VI", "🇻🇮", "Virgin Islands (U.S.)", false},
		{"VN", "🇻🇳", "Viet Nam", false},
		{"VU", "🇻🇺", "Vanuatu", false},
		{"WF", "🇼🇫", "Wallis and Futuna", false},
		{"WS", "🇼🇸", "Samoa", false},
		{"YE", "🇾🇪", "Yemen", false},
		{"YT", "🇾🇹", "Mayotte", false},
		{"ZA", "🇿🇦", "South Africa", false},
		{"ZM", "🇿🇲", "Zambia", false},
		{"ZW", "🇿🇼", "Zimbabwe", false},
	}
)
